<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ConsoleOutputEncoding>utf-16</ConsoleOutputEncoding>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lab3_3_DAL\Lab3_3_DAL.csproj" />
  </ItemGroup>
</Project>
